version: '3'

services:
  postgres:
    hostname: postgresql
    container_name: postgresql
    image: custom-postgres:latest
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data_init.sql:/docker-entrypoint-initdb.d/data_init.sql

networks:
  flowdesk:
    driver: bridge
